// Common occupation categories — relevant to a yeshiva/Jewish-community fundraising context,
// but works for any nonprofit. The user can also enter a free-text "Other" by leaving the
// dropdown on the empty option and typing in the adjacent free-text field.
export const OCCUPATION_CATEGORIES = [
  { value: '', label: '— Select category —' },
  { value: 'business_owner', label: 'Business owner' },
  { value: 'employee', label: 'Employee' },
  { value: 'self_employed', label: 'Self-employed' },
  { value: 'kli_kodesh', label: 'Kli Kodesh (Rabbi / Educator)' },
  { value: 'professional', label: 'Professional (Doctor, Lawyer, CPA, etc.)' },
  { value: 'real_estate', label: 'Real estate' },
  { value: 'finance', label: 'Finance / Investor' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'tech', label: 'Tech / Engineering' },
  { value: 'retail', label: 'Retail / Wholesale' },
  { value: 'construction', label: 'Construction / Trades' },
  { value: 'retired', label: 'Retired' },
  { value: 'student', label: 'Student / Kollel' },
  { value: 'philanthropist', label: 'Philanthropist / Foundation' },
  { value: 'other', label: 'Other' },
] as const;

// Most-common countries first (US, Israel, Canada, UK), then alphabetical for the rest.
// User can stick with the default empty option to leave country blank.
export const COUNTRIES: ReadonlyArray<{ code: string; name: string }> = [
  { code: 'US', name: 'United States' },
  { code: 'IL', name: 'Israel' },
  { code: 'CA', name: 'Canada' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BR', name: 'Brazil' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CO', name: 'Colombia' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'EG', name: 'Egypt' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'GR', name: 'Greece' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IN', name: 'India' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IT', name: 'Italy' },
  { code: 'JP', name: 'Japan' },
  { code: 'KR', name: 'Korea, South' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MX', name: 'Mexico' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NO', name: 'Norway' },
  { code: 'PA', name: 'Panama' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SG', name: 'Singapore' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'ES', name: 'Spain' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TR', name: 'Turkey' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
];
